### ISSUE TITLE
Are we using this package ?

### ISSUE THREAD

**Issue by bitsnaps** [CorpoSense/tresorie#23]
We're using two packages for the same purposes, do we need this one?
https://github.com/CorpoSense/tresorie/blob/d4ca1a6c5a5a1db320376b290ebc3658a5a27aa0/composer.json#L37

**Comment by raezon** [comment]
yes it is responsible for generating of code a bar

**Comment by raezon** [comment]
no we are not using it we stop using it

**Comment by bitsnaps** [comment]
Package removed 2adddbeeee5e916c5cacff3a1b5eab27e4469407.
