### ISSUE TITLE
Test Db

### ISSUE THREAD

**Issue by raezon** [CorpoSense/tresorie#3]
### In the acceptance test when I a lunch test everything is working fine.

_but instead of fetching data of the  yalitresoredb_test he getting data from yalitresoredb even the configuration of the test DB said the opposite.

I've launched:tests\bin\yii.bat serve, selenium server, chrome driver.

but I have the same issue._

**Comment by bitsnaps** [comment]
Could you elaborate? can I see the log?

**Comment by raezon** [comment]
I did not get you well when you said log their no error mentioned in the terminal.
I did find this
`
If you are using PhpBrowser or WebDriver module, they make requests to the website under test over HTTP and Codeception has no control over the configuration and execution of the website.
`
mentioned on this link :
https://stackoverflow.com/questions/40279645/codeception-acceptance-test-running-on-the-dev-database-instead-of-the-test-data

**Comment by raezon** [comment]
well, I did solve the issue .
the thing is you must precise the full URL using this kind of syntax :
`index-test.php?r=admin/decaissement` instead of
 `index.php?r=admin/decaissement`
 on web folder
 since each index has its proper configuration inner the config folder, so I did solve the issue.
