### ISSUE TITLE
gitpod  php yii serve 

### ISSUE THREAD

**Issue by raezon** [CorpoSense/tresorie#4]
running our application on 127.0.0.1 or localhost causes some redirection to localhost which causes errors.

it works fine with PHP Yii serve 0.0.0.0 , which solves the issue but still not clear why it works and why the errors happened.

**Comment by bitsnaps** [comment]
The issue I got in gitpod is about `PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /workspace/tresorie/config/db.php:2` see the workaround [here](https://stackoverflow.com/questions/8656089/solution-for-fatal-error-maximum-function-nesting-level-of-100-reached-abor), on gitpod this can be [customized](https://github.com/gitpod-io/gitpod/issues/943).

**Comment by bitsnaps** [comment]
Fixed in gitopd config.
