### ISSUE TITLE
check mail service usario 

### ISSUE THREAD

**Issue by raezon** [CorpoSense/tresorie#7]
We did create a user from the admin panel but couldn't be created and get some error due to mailer

**Comment by bitsnaps** [comment]
Have you tried to use any of fake-mailer solution like [eMailer](https://www.yiiframework.com/extension/mailer) or [YiiMailer](https://www.yiiframework.com/wiki/468/send-mail-using-yiimail-extension), you could also use [Mailtrap](https://mailtrap.io/), and don't forget config `useFileTransport` to store emails in file, so you can check them locally.
